name: AsyncAPI documents processing

on:
  push:
    branches: [ master ]

jobs:
  generate:
    runs-on: ubuntu-latest
    name: phraze api
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
           
      - name: Generating HTML from my AsyncAPI document
        uses: asyncapi/github-action-for-generator@v2.0.2
        
      - name: Deploy GH page
        uses: JamesIves/github-pages-deploy-action@3.4.2
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: generated-html 
